name: fetch
on:
  workflow_dispatch:
  # push:
  schedule:
    - cron: 0 */2 * * *
jobs:
  run:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm ci
      - run: node fetch_url.js
      - name: Push to repository
        run: |
          # actions自动提交
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update by GitHub Actions"
          git push
